# SPDX-FileCopyrightText: 2026 Julian Brost <julian@0x4a42.net>
# SPDX-License-Identifier: MIT

name: Arch Package
on: [push, pull_request]

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker.io/archlinux:base-devel
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install build tools
        run: pacman -Syu --noconfirm namcap

      - name: Create build user
        run: useradd -m -s /bin/bash build && chown -R build .

      - name: Build package
        run: runuser -u build -- makepkg

      - name: Lint package
        run: runuser -u build -- namcap PKGBUILD *.pkg.tar.zst
